#Requires -Version 5.1
<#
.SYNOPSIS
  Sets up the standalone Android Emulator (no Android Studio) and creates an AVD.

.DESCRIPTION
  1. Checks Java (does not install it)
  2. Downloads the official Android command-line tools if missing
  3. Sets ANDROID_HOME and PATH (user level)
  4. Accepts SDK licenses
  5. Lists available system images and platforms; you choose
  6. Installs emulator, platform-tools, the platform and the system image
  7. Lets you choose a device profile and creates the AVD
  8. Optionally creates a desktop shortcut that opens a launcher window where you
     pick GPU mode, audio, network speed, boot options, etc. before the emulator starts

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File .\setup-android-emulator.ps1
  powershell -ExecutionPolicy Bypass -File .\setup-android-emulator.ps1 -SdkRoot D:\Android\sdk

.EXAMPLE
  # Already installed? Only (re)create the launcher + shortcut:
  powershell -ExecutionPolicy Bypass -File .\setup-android-emulator.ps1 -ShortcutOnly
#>
[CmdletBinding()]
param(
    [string]$SdkRoot = 'C:\Android\sdk',
    [string]$AvdName = '',
    [string]$Device  = '',
    [switch]$ShortcutOnly
)

$ErrorActionPreference = 'Stop'
$ProgressPreference    = 'SilentlyContinue'

# ----------------------------------------------------------------- helpers
function Write-Step([string]$Text) {
    Write-Host ''
    Write-Host "=== $Text" -ForegroundColor Green
}

# Runs a command block; stderr warnings from Java tools must not abort the script
function Invoke-Native([scriptblock]$Cmd) {
    $old = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try { & $Cmd } finally { $ErrorActionPreference = $old }
}

function Read-Choice {
    param([string]$Title, [string[]]$Items, [int]$Default = 1)
    Write-Host ''
    Write-Host $Title -ForegroundColor Cyan
    for ($i = 0; $i -lt $Items.Count; $i++) {
        $mark = ''
        if (($i + 1) -eq $Default) { $mark = '  (default)' }
        Write-Host ('  [{0}] {1}{2}' -f ($i + 1), $Items[$i], $mark)
    }
    while ($true) {
        $r = Read-Host ('Select 1-{0} [Enter = {1}]' -f $Items.Count, $Default)
        if ([string]::IsNullOrWhiteSpace($r)) { return ($Default - 1) }
        $n = 0
        if ([int]::TryParse($r, [ref]$n) -and $n -ge 1 -and $n -le $Items.Count) { return ($n - 1) }
        Write-Host 'Invalid choice, try again.' -ForegroundColor Yellow
    }
}

function Add-UserPath([string]$Dir) {
    $user = [Environment]::GetEnvironmentVariable('Path', 'User')
    if (-not $user) { $user = '' }
    $parts = @($user -split ';' | Where-Object { $_ })
    if ($parts -notcontains $Dir) {
        [Environment]::SetEnvironmentVariable('Path', (($parts + $Dir) -join ';'), 'User')
    }
    if ((@($env:Path -split ';')) -notcontains $Dir) { $env:Path = "$env:Path;$Dir" }
}

function Get-VersionKey([string]$Api) {
    $v = $Api -replace '^android-', ''
    if ($v -notmatch '^\d+(\.\d+)?$') { return [version]'0.0' }
    if ($v -notmatch '\.') { $v = "$v.0" }
    return [version]$v
}

function Get-TagDescription([string]$Tag) {
    $desc = switch -Regex ($Tag) {
        '^default'               { 'AOSP (no Google services)'; break }
        '^google_apis_playstore' { 'Google APIs + Play Store (no adb root)'; break }
        '^google_apis'           { 'Google APIs, no Play Store (good for testing, adb root works)'; break }
        default                  { $Tag }
    }
    if ($Tag -match 'ps16k') { $desc += '  [16 KB page size]' }
    return $desc
}

# ----------------------------------------------------------------- launcher UI + shortcut
# The launcher window (WinForms) is stored here and written to <SdkRoot>\launcher\ on demand.
$LauncherSource = @'
#Requires -Version 5.1
<#
  Android Emulator Launcher
  Generated by setup-android-emulator.ps1. Shows an options window and then
  starts the emulator with the flags you selected. Safe to edit or delete.
#>
[CmdletBinding()]
param(
    [string]$SdkRoot = 'C:\Android\sdk',
    [string]$Avd     = ''
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
try {
    Add-Type -Namespace Win32 -Name Dpi -MemberDefinition '[System.Runtime.InteropServices.DllImport("user32.dll")] public static extern bool SetProcessDPIAware();'
    [void][Win32.Dpi]::SetProcessDPIAware()
} catch { }
[System.Windows.Forms.Application]::EnableVisualStyles()

function Show-Msg([string]$Text, [string]$Title = 'Android Emulator Launcher', [string]$Icon = 'Information') {
    [void][System.Windows.Forms.MessageBox]::Show($Text, $Title, 'OK', $Icon)
}

# The window has no console (it is started hidden), so show unexpected errors in a dialog
trap {
    Show-Msg ($_ | Out-String) 'Launcher error' 'Error'
    exit 1
}

$emulator = Join-Path $SdkRoot 'emulator\emulator.exe'
if (-not (Test-Path -LiteralPath $emulator)) {
    Show-Msg "emulator.exe was not found at:`n$emulator`n`nRe-run setup-android-emulator.ps1 or fix the -SdkRoot argument of this shortcut." 'Launcher' 'Error'
    exit 1
}
$env:ANDROID_HOME     = $SdkRoot
$env:ANDROID_SDK_ROOT = $SdkRoot

$dataDir      = Join-Path $env:LOCALAPPDATA 'AndroidEmulatorLauncher'
$settingsFile = Join-Path $dataDir 'settings.json'
$logOut       = Join-Path $dataDir 'last-run.out.log'
$logErr       = Join-Path $dataDir 'last-run.err.log'
New-Item -ItemType Directory -Force -Path $dataDir | Out-Null

# ----------------------------------------------------------------- available AVDs
$avds = @()
try {
    $avds = @(& $emulator -list-avds 2>$null | ForEach-Object { "$_".Trim() } | Where-Object { $_ -match '^[A-Za-z0-9._-]+$' })
} catch { }
if ($avds.Count -eq 0) {
    $avdHome = Join-Path $env:USERPROFILE '.android\avd'
    if ($env:ANDROID_AVD_HOME) { $avdHome = $env:ANDROID_AVD_HOME }
    if (Test-Path -LiteralPath $avdHome) {
        $avds = @(Get-ChildItem -LiteralPath $avdHome -Filter '*.ini' -File | ForEach-Object { $_.BaseName })
    }
}

# ----------------------------------------------------------------- settings
$s = [ordered]@{
    Avd = ''; NoAudio = $true; Gpu = 'host'; NetSpeed = 'full'; NetDelay = 'none'
    NoBootAnim = $false; ColdBoot = $false; NoSnapSave = $false; ReadOnly = $false; NoWindow = $false
    UseMem = $false; Mem = 4096; UseCores = $false; Cores = 4; Extra = ''; CloseAfter = $true
}
if (Test-Path -LiteralPath $settingsFile) {
    try {
        $j = Get-Content -LiteralPath $settingsFile -Raw | ConvertFrom-Json
        foreach ($k in @($s.Keys)) {
            if ($null -ne $j.$k) { $s[$k] = $j.$k }
        }
    } catch { }
}

# ----------------------------------------------------------------- small UI helpers
function New-Lbl([string]$Text, [int]$X, [int]$Y) {
    $c = New-Object System.Windows.Forms.Label
    $c.Text = $Text
    $c.AutoSize = $true
    $c.Location = New-Object System.Drawing.Point($X, $Y)
    return $c
}
function New-Chk([string]$Text, [int]$X, [int]$Y, [int]$W = 250) {
    $c = New-Object System.Windows.Forms.CheckBox
    $c.Text = $Text
    $c.Location = New-Object System.Drawing.Point($X, $Y)
    $c.Size = New-Object System.Drawing.Size($W, 22)
    return $c
}
function New-Cmb([string[]]$Items, [int]$X, [int]$Y, [int]$W) {
    $c = New-Object System.Windows.Forms.ComboBox
    $c.DropDownStyle = 'DropDownList'
    $c.Location = New-Object System.Drawing.Point($X, $Y)
    $c.Size = New-Object System.Drawing.Size($W, 24)
    foreach ($i in $Items) { [void]$c.Items.Add($i) }
    return $c
}
function New-Grp([string]$Text, [int]$Y, [int]$H) {
    $g = New-Object System.Windows.Forms.GroupBox
    $g.Text = $Text
    $g.Location = New-Object System.Drawing.Point(16, $Y)
    $g.Size = New-Object System.Drawing.Size(548, $H)
    return $g
}
function New-Num([int]$Min, [int]$Max, [int]$Step, [int]$X, [int]$Y, [int]$W) {
    $n = New-Object System.Windows.Forms.NumericUpDown
    $n.Minimum = $Min; $n.Maximum = $Max; $n.Increment = $Step
    $n.Location = New-Object System.Drawing.Point($X, $Y)
    $n.Size = New-Object System.Drawing.Size($W, 24)
    return $n
}
function Set-Cmb($Combo, $Value, [int]$FallbackIndex = 0) {
    $idx = $Combo.Items.IndexOf([string]$Value)
    if ($idx -ge 0) { $Combo.SelectedIndex = $idx }
    elseif ($Combo.Items.Count -gt 0) { $Combo.SelectedIndex = $FallbackIndex }
}
function Set-Num($Num, $Value) {
    $v = 0
    if ([int]::TryParse([string]$Value, [ref]$v)) {
        $Num.Value = [Math]::Max($Num.Minimum, [Math]::Min($Num.Maximum, $v))
    }
}

# ----------------------------------------------------------------- form
$form = New-Object System.Windows.Forms.Form
$form.Text = 'Android Emulator Launcher'
$form.AutoScaleDimensions = New-Object System.Drawing.SizeF(96, 96)
$form.AutoScaleMode = 'Dpi'
$form.ClientSize = New-Object System.Drawing.Size(580, 736)
$form.StartPosition = 'CenterScreen'
$form.FormBorderStyle = 'FixedDialog'
$form.MaximizeBox = $false
$form.Font = New-Object System.Drawing.Font('Segoe UI', 9)
try { $form.Icon = [System.Drawing.Icon]::ExtractAssociatedIcon($emulator) } catch { }

$tip = New-Object System.Windows.Forms.ToolTip
$tip.AutoPopDelay = 15000

$hdr = New-Lbl 'Android Emulator' 14 8
$hdr.Font = New-Object System.Drawing.Font('Segoe UI Semibold', 15)
$sub = New-Lbl 'Choose your options, then press Launch.' 16 40
$sub.ForeColor = [System.Drawing.Color]::DimGray
$form.Controls.Add($hdr); $form.Controls.Add($sub)

# ---- Virtual device
$gAvd = New-Grp 'Virtual device' 66 60
$cmbAvd = New-Cmb $avds 16 24 516
$gAvd.Controls.Add($cmbAvd)
$form.Controls.Add($gAvd)

# ---- Graphics & audio
$gGfx = New-Grp 'Graphics and audio' 136 100
$gGfx.Controls.Add((New-Lbl 'GPU mode' 16 30))
$cmbGpu = New-Cmb @('host', 'auto', 'swiftshader_indirect', 'angle_indirect', 'guest', 'off') 100 26 220
$chkNoAudio = New-Chk 'Disable audio  (-no-audio)' 16 62 250
$chkNoAnim  = New-Chk 'Skip boot animation  (-no-boot-anim)' 280 62 260
$gGfx.Controls.AddRange(@($cmbGpu, $chkNoAudio, $chkNoAnim))
$form.Controls.Add($gGfx)
$tip.SetToolTip($cmbGpu, "host = use your real GPU (fastest)`nauto = let the emulator decide`nswiftshader_indirect / angle_indirect = software or ANGLE rendering (use if host gives glitches)`nguest = render inside Android (slow)")

# ---- Network
$gNet = New-Grp 'Network' 246 70
$gNet.Controls.Add((New-Lbl 'Speed' 16 32))
$cmbSpeed = New-Cmb @('full', 'lte', 'hsdpa', 'hspa', 'umts', 'evdo', 'edge', 'gprs', 'gsm') 70 28 180
$gNet.Controls.Add((New-Lbl 'Latency' 290 32))
$cmbDelay = New-Cmb @('none', 'umts', 'gprs', 'edge') 350 28 180
$gNet.Controls.AddRange(@($cmbSpeed, $cmbDelay))
$form.Controls.Add($gNet)
$tip.SetToolTip($cmbSpeed, '-netspeed: simulated network speed. "full" = no throttling.')
$tip.SetToolTip($cmbDelay, '-netdelay: simulated network latency. "none" = no delay.')

# ---- Startup & storage
$gBoot = New-Grp 'Startup and storage' 326 120
$chkCold   = New-Chk 'Cold boot  (-no-snapshot-load)' 16 26 260
$chkNoSave = New-Chk "Don't save state  (-no-snapshot-save)" 280 26 260
$chkRO     = New-Chk 'Read-only  (-read-only)' 16 54 260
$chkNoWin  = New-Chk 'Headless, no window  (-no-window)' 280 54 260
$chkWipe   = New-Chk 'Wipe data, factory reset  (-wipe-data)' 16 82 260
$gBoot.Controls.AddRange(@($chkCold, $chkNoSave, $chkRO, $chkNoWin, $chkWipe))
$form.Controls.Add($gBoot)
$tip.SetToolTip($chkCold,   'Boots Android from scratch instead of resuming the saved snapshot. Slower start, but fixes a stuck state.')
$tip.SetToolTip($chkNoSave, 'Keeps the next start identical: the current session is not saved as a snapshot.')
$tip.SetToolTip($chkRO,     'Nothing is written to the virtual device. Also allows several instances of the same AVD.')
$tip.SetToolTip($chkWipe,   'Erases all apps and data on this AVD. You will be asked to confirm, and this is never remembered.')

# ---- Performance
$gPerf = New-Grp 'Performance (optional overrides)' 456 64
$chkMem   = New-Chk 'RAM (MB)  (-memory)' 16 28 150
$numMem   = New-Num 512 32768 512 170 26 90
$chkCores = New-Chk 'CPU cores  (-cores)' 290 28 140
$numCores = New-Num 1 32 1 434 26 70
$gPerf.Controls.AddRange(@($chkMem, $numMem, $chkCores, $numCores))
$form.Controls.Add($gPerf)

# ---- Extra args
$form.Controls.Add((New-Lbl 'Extra arguments (optional, e.g. -dns-server 8.8.8.8 -camera-back webcam0)' 16 530))
$txtExtra = New-Object System.Windows.Forms.TextBox
$txtExtra.Location = New-Object System.Drawing.Point(16, 552)
$txtExtra.Size = New-Object System.Drawing.Size(548, 24)
$form.Controls.Add($txtExtra)

# ---- Command preview
$form.Controls.Add((New-Lbl 'Command that will run:' 16 584))
$txtPreview = New-Object System.Windows.Forms.TextBox
$txtPreview.Location = New-Object System.Drawing.Point(16, 606)
$txtPreview.Size = New-Object System.Drawing.Size(548, 54)
$txtPreview.Multiline = $true
$txtPreview.ReadOnly = $true
$txtPreview.ScrollBars = 'Vertical'
$txtPreview.BackColor = [System.Drawing.Color]::White
$txtPreview.Font = New-Object System.Drawing.Font('Consolas', 9)
$form.Controls.Add($txtPreview)

$chkClose = New-Chk 'Close this window after launching' 16 668 300
$form.Controls.Add($chkClose)

# ---- Buttons
$btnLaunch = New-Object System.Windows.Forms.Button
$btnLaunch.Text = 'Launch'
$btnLaunch.Location = New-Object System.Drawing.Point(16, 696)
$btnLaunch.Size = New-Object System.Drawing.Size(170, 34)
$btnLaunch.Font = New-Object System.Drawing.Font('Segoe UI Semibold', 10)
$btnCopy = New-Object System.Windows.Forms.Button
$btnCopy.Text = 'Copy command'
$btnCopy.Location = New-Object System.Drawing.Point(196, 696)
$btnCopy.Size = New-Object System.Drawing.Size(130, 34)
$btnExit = New-Object System.Windows.Forms.Button
$btnExit.Text = 'Close'
$btnExit.Location = New-Object System.Drawing.Point(434, 696)
$btnExit.Size = New-Object System.Drawing.Size(130, 34)
$form.Controls.AddRange(@($btnLaunch, $btnCopy, $btnExit))
$form.AcceptButton = $btnLaunch
$form.CancelButton = $btnExit

# ----------------------------------------------------------------- logic
function Get-ArgString {
    $a = @()
    if ($cmbAvd.Text) { $a += '-avd'; $a += $cmbAvd.Text }
    if ($chkNoAudio.Checked) { $a += '-no-audio' }
    if ($cmbGpu.Text)   { $a += '-gpu';      $a += $cmbGpu.Text }
    if ($cmbDelay.Text) { $a += '-netdelay'; $a += $cmbDelay.Text }
    if ($cmbSpeed.Text) { $a += '-netspeed'; $a += $cmbSpeed.Text }
    if ($chkNoAnim.Checked)  { $a += '-no-boot-anim' }
    if ($chkCold.Checked)    { $a += '-no-snapshot-load' }
    if ($chkNoSave.Checked)  { $a += '-no-snapshot-save' }
    if ($chkRO.Checked)      { $a += '-read-only' }
    if ($chkNoWin.Checked)   { $a += '-no-window' }
    if ($chkWipe.Checked)    { $a += '-wipe-data' }
    if ($chkMem.Checked)     { $a += '-memory'; $a += [string][int]$numMem.Value }
    if ($chkCores.Checked)   { $a += '-cores';  $a += [string][int]$numCores.Value }
    $line = $a -join ' '
    $x = $txtExtra.Text.Trim()
    if ($x) { $line = "$line $x" }
    return $line
}

function Update-Preview {
    $numMem.Enabled   = $chkMem.Checked
    $numCores.Enabled = $chkCores.Checked
    $txtPreview.Text  = '& "' + $emulator + '" ' + (Get-ArgString)
}

function Save-Settings {
    try {
        [ordered]@{
            Avd = $cmbAvd.Text; NoAudio = $chkNoAudio.Checked; Gpu = $cmbGpu.Text
            NetSpeed = $cmbSpeed.Text; NetDelay = $cmbDelay.Text
            NoBootAnim = $chkNoAnim.Checked; ColdBoot = $chkCold.Checked; NoSnapSave = $chkNoSave.Checked
            ReadOnly = $chkRO.Checked; NoWindow = $chkNoWin.Checked
            UseMem = $chkMem.Checked; Mem = [int]$numMem.Value
            UseCores = $chkCores.Checked; Cores = [int]$numCores.Value
            Extra = $txtExtra.Text; CloseAfter = $chkClose.Checked
        } | ConvertTo-Json | Set-Content -LiteralPath $settingsFile -Encoding UTF8
    } catch { }
}

# restore saved values (the shortcut's -Avd wins over the last-used one)
$wantedAvd = $s.Avd
if ($Avd) { $wantedAvd = $Avd }
Set-Cmb $cmbAvd $wantedAvd 0
Set-Cmb $cmbGpu $s.Gpu 0
Set-Cmb $cmbSpeed $s.NetSpeed 0
Set-Cmb $cmbDelay $s.NetDelay 0
$chkNoAudio.Checked = [bool]$s.NoAudio
$chkNoAnim.Checked  = [bool]$s.NoBootAnim
$chkCold.Checked    = [bool]$s.ColdBoot
$chkNoSave.Checked  = [bool]$s.NoSnapSave
$chkRO.Checked      = [bool]$s.ReadOnly
$chkNoWin.Checked   = [bool]$s.NoWindow
$chkMem.Checked     = [bool]$s.UseMem
$chkCores.Checked   = [bool]$s.UseCores
Set-Num $numMem $s.Mem
Set-Num $numCores $s.Cores
$txtExtra.Text      = [string]$s.Extra
$chkClose.Checked   = [bool]$s.CloseAfter

$onChange = { Update-Preview }
foreach ($c in @($chkNoAudio, $chkNoAnim, $chkCold, $chkNoSave, $chkRO, $chkNoWin, $chkWipe, $chkMem, $chkCores)) {
    $c.Add_CheckedChanged($onChange)
}
foreach ($c in @($cmbAvd, $cmbGpu, $cmbSpeed, $cmbDelay)) { $c.Add_SelectedIndexChanged($onChange) }
foreach ($c in @($numMem, $numCores)) { $c.Add_ValueChanged($onChange) }
$txtExtra.Add_TextChanged($onChange)

if ($avds.Count -eq 0) {
    $btnLaunch.Enabled = $false
    $txtPreview.Text = 'No virtual devices found. Run setup-android-emulator.ps1 to create one.'
} else {
    Update-Preview
}

$timer = New-Object System.Windows.Forms.Timer
$timer.Interval = 1500
$timer.Add_Tick({ $timer.Stop(); $btnCopy.Text = 'Copy command' })
$btnCopy.Add_Click({
    Set-Clipboard -Value $txtPreview.Text
    $btnCopy.Text = 'Copied!'
    $timer.Stop(); $timer.Start()
})

$btnExit.Add_Click({ $form.Close() })
$form.Add_FormClosing({ Save-Settings })

$btnLaunch.Add_Click({
    if (-not $cmbAvd.Text) {
        Show-Msg 'Please select a virtual device first.' 'Android Emulator Launcher' 'Warning'
        return
    }
    if ($chkWipe.Checked) {
        $r = [System.Windows.Forms.MessageBox]::Show(
            "This will ERASE all apps and data on '$($cmbAvd.Text)' (factory reset).`n`nContinue?",
            'Wipe user data', 'YesNo', 'Warning')
        if ($r -ne 'Yes') { return }
    }
    Save-Settings
    $argLine = Get-ArgString
    $btnLaunch.Enabled = $false
    $btnLaunch.Text = 'Starting...'
    [System.Windows.Forms.Application]::DoEvents()
    $closing = $false
    try {
        $p = Start-Process -FilePath $emulator -ArgumentList $argLine `
                -WorkingDirectory (Split-Path -Parent $emulator) -WindowStyle Hidden -PassThru `
                -RedirectStandardOutput $logOut -RedirectStandardError $logErr
        if ($p.WaitForExit(6000)) {
            $tail = (@($logErr, $logOut | ForEach-Object {
                if (Test-Path -LiteralPath $_) { Get-Content -LiteralPath $_ -Tail 12 }
            }) -join "`n").Trim()
            if (-not $tail) { $tail = '(no output)' }
            Show-Msg ("The emulator exited right after starting (exit code $($p.ExitCode)).`n`n$tail`n`nFull log: $dataDir") 'Emulator did not start' 'Error'
        } elseif ($chkClose.Checked) {
            $closing = $true
            $form.Close()
        }
    } catch {
        Show-Msg $_.Exception.Message 'Could not start the emulator' 'Error'
    } finally {
        if (-not $closing) {
            $btnLaunch.Enabled = $true
            $btnLaunch.Text = 'Launch'
        }
    }
})

[void]$form.ShowDialog()
'@

function New-LauncherLink {
    param([string]$LinkPath, [string]$LauncherPs1, [string]$SdkRoot, [string]$AvdName)
    $ws  = New-Object -ComObject WScript.Shell
    $lnk = $ws.CreateShortcut($LinkPath)
    $lnk.TargetPath = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $argLine = '-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "{0}" -SdkRoot "{1}"' -f $LauncherPs1, $SdkRoot
    if ($AvdName) { $argLine += (' -Avd "{0}"' -f $AvdName) }
    $lnk.Arguments        = $argLine
    $lnk.WorkingDirectory = $SdkRoot
    $lnk.IconLocation     = (Join-Path $SdkRoot 'emulator\emulator.exe') + ',0'
    $lnk.WindowStyle      = 7          # minimized, so no console flash
    $lnk.Description      = 'Android Emulator launcher'
    $lnk.Save()
}

function New-EmulatorShortcut {
    param([string]$SdkRoot, [string]$AvdName)

    $ans = Read-Host 'Create a desktop shortcut that opens the emulator launcher window? [Y/n]'
    if ($ans -match '^[nN]') { Write-Host 'Skipped.'; return }

    $dir = Join-Path $SdkRoot 'launcher'
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    $ps1 = Join-Path $dir 'emulator-launcher.ps1'
    Set-Content -Path $ps1 -Value $LauncherSource -Encoding UTF8   # BOM, so Windows PowerShell reads it correctly

    $desktop = [Environment]::GetFolderPath('Desktop')
    $link = Join-Path $desktop 'Android Emulator.lnk'
    New-LauncherLink -LinkPath $link -LauncherPs1 $ps1 -SdkRoot $SdkRoot -AvdName $AvdName
    Write-Host "Desktop shortcut created: $link" -ForegroundColor Green

    $ans = Read-Host 'Also add it to the Start Menu? [y/N]'
    if ($ans -match '^[yY]') {
        $programs = [Environment]::GetFolderPath('Programs')
        $link2 = Join-Path $programs 'Android Emulator.lnk'
        New-LauncherLink -LinkPath $link2 -LauncherPs1 $ps1 -SdkRoot $SdkRoot -AvdName $AvdName
        Write-Host "Start Menu shortcut created: $link2" -ForegroundColor Green
    }
    Write-Host "Launcher script: $ps1"
    Write-Host 'Your last-used options are remembered in %LOCALAPPDATA%\AndroidEmulatorLauncher\settings.json'
}

if ($ShortcutOnly) {
    if (-not (Test-Path (Join-Path $SdkRoot 'emulator\emulator.exe'))) {
        throw "emulator.exe not found in $SdkRoot\emulator. Run the full setup first (or pass -SdkRoot)."
    }
    Write-Step 'Launcher shortcut'
    New-EmulatorShortcut -SdkRoot $SdkRoot -AvdName $AvdName
    return
}

# ----------------------------------------------------------------- 1. Java
Write-Step '1/7  Checking Java'
$javaExe = $null
if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME 'bin\java.exe'))) {
    $javaExe = Join-Path $env:JAVA_HOME 'bin\java.exe'
} else {
    if ($env:JAVA_HOME) {
        Write-Warning "JAVA_HOME points to a missing folder ($env:JAVA_HOME); ignoring it for this run."
        Remove-Item Env:JAVA_HOME
    }
    $cmd = Get-Command java.exe -ErrorAction SilentlyContinue
    if ($cmd) { $javaExe = $cmd.Source }
}
if (-not $javaExe) {
    throw 'Java was not found. Install a JDK (17 or 21 recommended) and set JAVA_HOME, then run again.'
}
$javaVer = Invoke-Native { & $javaExe -version 2>&1 | Select-Object -First 1 | ForEach-Object { "$_" } }
Write-Host "Using: $javaExe"
Write-Host "       $javaVer"
$env:SKIP_JDK_VERSION_CHECK = '1'   # newer JDKs print "27", which old checks misread

# ----------------------------------------------------------------- 2. command-line tools
Write-Step '2/7  Android command-line tools'
$sdkmanager = Join-Path $SdkRoot 'cmdline-tools\latest\bin\sdkmanager.bat'
$avdmanager = Join-Path $SdkRoot 'cmdline-tools\latest\bin\avdmanager.bat'

if (Test-Path $sdkmanager) {
    Write-Host "Already present in $SdkRoot"
} else {
    New-Item -ItemType Directory -Force -Path $SdkRoot | Out-Null
    Write-Host 'Looking up the current command-line tools download...'
    $zipUrl = $null
    try {
        $resp = Invoke-WebRequest -UseBasicParsing 'https://dl.google.com/android/repository/repository2-3.xml'
        [xml]$repo = $resp.Content
        $pkgs = @($repo.GetElementsByTagName('remotePackage') | Where-Object { $_.path -eq 'cmdline-tools;latest' })
        $stable = @($pkgs | Where-Object { $_.channelRef.ref -eq 'channel-0' })
        if ($stable.Count -gt 0) { $pkgs = $stable }
        $best = $pkgs | Sort-Object { [int]$_.revision.major }, { [int]$_.revision.minor } -Descending | Select-Object -First 1
        $arc  = $best.archives.archive | Where-Object { $_.'host-os' -eq 'windows' } | Select-Object -First 1
        if ($arc) { $zipUrl = 'https://dl.google.com/android/repository/' + $arc.complete.url }
    } catch {
        Write-Warning "Could not read the repository manifest: $($_.Exception.Message)"
    }
    if (-not $zipUrl) {
        Write-Host 'Open https://developer.android.com/studio#command-line-tools-only,'
        Write-Host 'copy the Windows "Command line tools only" zip link and paste it here.'
        $zipUrl = (Read-Host 'Zip URL').Trim()
    }

    $tmp = Join-Path $env:TEMP ('android-cmdline-' + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Force -Path $tmp | Out-Null
    $zip = Join-Path $tmp 'cmdline-tools.zip'
    Write-Host "Downloading $zipUrl"
    Invoke-WebRequest -UseBasicParsing $zipUrl -OutFile $zip
    Expand-Archive -Path $zip -DestinationPath $tmp -Force

    $dest = Join-Path $SdkRoot 'cmdline-tools\latest'
    New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
    if (Test-Path $dest) { Remove-Item -Recurse -Force $dest }
    Move-Item -Path (Join-Path $tmp 'cmdline-tools') -Destination $dest
    Remove-Item -Recurse -Force $tmp
    if (-not (Test-Path $sdkmanager)) { throw "sdkmanager not found after extraction at $sdkmanager" }
    Write-Host 'Command-line tools installed.'
}

# ----------------------------------------------------------------- 3. environment
Write-Step '3/7  Environment variables'
[Environment]::SetEnvironmentVariable('ANDROID_HOME',     $SdkRoot, 'User')
[Environment]::SetEnvironmentVariable('ANDROID_SDK_ROOT', $SdkRoot, 'User')
$env:ANDROID_HOME     = $SdkRoot
$env:ANDROID_SDK_ROOT = $SdkRoot
Add-UserPath (Join-Path $SdkRoot 'cmdline-tools\latest\bin')
Add-UserPath (Join-Path $SdkRoot 'platform-tools')
Add-UserPath (Join-Path $SdkRoot 'emulator')
Write-Host "ANDROID_HOME = $SdkRoot"
Write-Host 'PATH updated (applies to NEW terminals).'

# ----------------------------------------------------------------- 4. licenses
Write-Step '4/7  Accepting SDK licenses'
Invoke-Native { 1..100 | ForEach-Object { 'y' } | & $sdkmanager "--sdk_root=$SdkRoot" --licenses | Out-Null }
Write-Host 'Done.'

# ----------------------------------------------------------------- 5. list + choose
Write-Step '5/7  Listing available packages (can take a minute)'
# Newer tools print names with slashes (system-images/android-37.2/...), older ones with ';'.
# The first run may also unpack the Android CLI, which can fail briefly; retry a few times.
$listText = ''
$bundles  = Join-Path $env:USERPROFILE '.android\cli\bundles'
for ($attempt = 1; $attempt -le 3; $attempt++) {
    if (Test-Path -LiteralPath $bundles) {
        Get-ChildItem -LiteralPath $bundles -Directory -Filter '*.extract' -ErrorAction SilentlyContinue |
            ForEach-Object { Remove-Item -LiteralPath $_.FullName -Recurse -Force -ErrorAction SilentlyContinue }
    }
    $out = Invoke-Native { & $sdkmanager "--sdk_root=$SdkRoot" --list 2>&1 | ForEach-Object { "$_" } }
    $listText = ($out | Out-String)
    if ($listText -match 'system-images[;/]') { break }
    if ($listText -match 'Access is denied') {
        Write-Warning "Attempt $attempt/3: the Android CLI could not unpack itself. Retrying in 5 s..."
        Start-Sleep -Seconds 5
    } else { break }
}
$listFile = Join-Path $env:TEMP 'sdkmanager-list.txt'
Set-Content -Path $listFile -Value $listText -Encoding UTF8
$slashNames = ($listText -match 'system-images/')

$arch = 'x86_64'
if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { $arch = 'arm64-v8a' }
Write-Host "CPU architecture -> using '$arch' images"

$all = foreach ($m in [regex]::Matches($listText, 'system-images[;/](android-[^;/\s|]+)[;/]([^;/\s|]+)[;/]([^;/\s|]+)')) {
    [pscustomobject]@{
        Api = $m.Groups[1].Value
        Tag = $m.Groups[2].Value
        Abi = $m.Groups[3].Value
        Id  = ('system-images;{0};{1};{2}' -f $m.Groups[1].Value, $m.Groups[2].Value, $m.Groups[3].Value)
    }
}
$all = @($all | Sort-Object Id -Unique | Where-Object { $_.Abi -eq $arch -and $_.Tag -match '^(default|google_apis)' })
if ($all.Count -eq 0) {
    Write-Host ''
    Write-Host 'First lines of what sdkmanager returned:' -ForegroundColor Yellow
    ($listText -split "[\r\n]+" | Where-Object { $_.Trim() } | Select-Object -First 20) | ForEach-Object { Write-Host "  $_" }
    throw "No system images found for $arch. Full output: $listFile"
}

$incPreview = Read-Host 'Include beta/preview releases? [y/N]'
if ($incPreview -notmatch '^[yY]') {
    $all = @($all | Where-Object { $_.Api -match '^android-\d+(\.\d+)?$' })
    if ($all.Count -eq 0) { throw 'No stable images found. Re-run and answer "y" to include previews.' }
}

# ---- system image
$apis = @($all | Group-Object Api | Sort-Object { Get-VersionKey $_.Name }, Name -Descending)
$apiLabels = foreach ($g in $apis) {
    $note = ''
    if ($g.Name -notmatch '^android-\d+(\.\d+)?$') { $note = '  [beta/preview]' }
    "{0}{1}" -f $g.Name, $note
}
$apiIdx = Read-Choice 'Android versions (newest first):' @($apiLabels) 1
$chosenApi = $apis[$apiIdx].Name

$variants = @($all | Where-Object { $_.Api -eq $chosenApi } | Sort-Object Tag)
$varLabels = foreach ($v in $variants) { '{0,-28} {1}' -f $v.Tag, (Get-TagDescription $v.Tag) }
$defVar = 1
for ($i = 0; $i -lt $variants.Count; $i++) { if ($variants[$i].Tag -eq 'google_apis') { $defVar = $i + 1; break } }
if ($defVar -eq 1) {
    for ($i = 0; $i -lt $variants.Count; $i++) { if ($variants[$i].Tag -eq 'google_apis_ps16k') { $defVar = $i + 1; break } }
}
$varIdx = Read-Choice "Image variants for $chosenApi ($arch):" @($varLabels) $defVar
$image = $variants[$varIdx]

# ---- platform
$platAll = @([regex]::Matches($listText, 'platforms[;/](android-[^;/\s|]+)') | ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique)
if ($incPreview -notmatch '^[yY]') { $platAll = @($platAll | Where-Object { $_ -match '^android-\d+(\.\d+)?$' }) }
$platAll = @($platAll | Sort-Object { Get-VersionKey $_ }, { $_ } -Descending)

$platformId = $null
if ($platAll.Count -gt 0) {
    $platLabels = @(foreach ($p in $platAll) {
        $note = ''
        if ($p -notmatch '^android-\d+(\.\d+)?$') { $note = '  [beta/preview/extension]' }
        if ($p -eq $chosenApi) { $note += '  <- matches your system image' }
        "{0}{1}" -f $p, $note
    })
    $platLabels += 'Skip (do not install a platform)'
    $defPlat = 1
    for ($i = 0; $i -lt $platAll.Count; $i++) { if ($platAll[$i] -eq $chosenApi) { $defPlat = $i + 1; break } }
    $platIdx = Read-Choice 'SDK Platform (newest first):' $platLabels $defPlat
    if ($platIdx -lt $platAll.Count) { $platformId = 'platforms;' + $platAll[$platIdx] }
}

$pkgs = @('emulator', 'platform-tools')
if ($platformId) { $pkgs += $platformId }
$pkgs += $image.Id

# ----------------------------------------------------------------- 6. install
Write-Step '6/7  Installing packages'
$installIds = @($pkgs | ForEach-Object { if ($slashNames) { $_ -replace ';', '/' } else { $_ } })
$installIds | ForEach-Object { Write-Host "  - $_" }
Invoke-Native { 1..100 | ForEach-Object { 'y' } | & $sdkmanager "--sdk_root=$SdkRoot" @installIds }
if ($LASTEXITCODE -ne 0) { throw "sdkmanager failed with exit code $LASTEXITCODE" }

# ----------------------------------------------------------------- 7. device + AVD
Write-Step '7/7  Device profile and virtual device'
if (-not $Device) {
    $out = Invoke-Native { & $avdmanager list device -c 2>&1 | ForEach-Object { "$_" } }
    $allDevs = @(($out | Out-String) -split "[\r\n]+" | ForEach-Object { $_.Trim() } |
        Where-Object { $_ -match '^[A-Za-z0-9_.\-]+$' } | Sort-Object -Unique)
    if ($allDevs.Count -eq 0) {
        Write-Warning 'avdmanager could not list device profiles; using a built-in list of common ones.'
        $builtin = @('pixel_9_pro_xl', 'pixel_9_pro', 'pixel_9', 'pixel_8_pro', 'pixel_8', 'pixel_7', 'pixel_6', 'pixel_tablet', 'pixel_fold', 'medium_phone', 'medium_tablet')
        $Device = $builtin[(Read-Choice 'Device profile:' $builtin 1)]
    } else {
        $cat = Read-Choice 'Which kind of device?' @(
            'Pixel phones (newest first)',
            'Tablets and foldables',
            'Wear OS / TV / Automotive / Desktop',
            'ALL device profiles'
        ) 1
        $devs = switch ($cat) {
            0 { @($allDevs | Where-Object { $_ -match '^pixel' -and $_ -notmatch 'tablet|fold|watch' }) }
            1 { @($allDevs | Where-Object { $_ -match 'tablet|fold|pixel_c|nexus_9|nexus_10|10\.1in|8in|7in' }) }
            2 { @($allDevs | Where-Object { $_ -match 'wear|tv|automotive|desktop|watch' }) }
            default { $allDevs }
        }
        if ($devs.Count -eq 0) { $devs = $allDevs }
        $devs = @($devs | Sort-Object { if ($_ -match '(\d+)') { [int]$Matches[1] } else { 0 } }, { $_ } -Descending)
        $Device = $devs[(Read-Choice 'Device profiles:' $devs 1)]
    }
}
Write-Host "Device: $Device"

if (-not $AvdName) {
    $suggest = ('{0}_{1}' -f $Device, ($chosenApi -replace '[^A-Za-z0-9]+', '_'))
    $AvdName = Read-Host "AVD name [Enter = $suggest]"
    if ([string]::IsNullOrWhiteSpace($AvdName)) { $AvdName = $suggest }
}
$AvdName = $AvdName -replace '[^A-Za-z0-9._-]', '_'

Invoke-Native { 'no' | & $avdmanager create avd -n $AvdName -k $image.Id -d $Device --force }
if ($LASTEXITCODE -ne 0) { throw "avdmanager failed with exit code $LASTEXITCODE (see output above)" }

# ----------------------------------------------------------------- finish
$emulator = Join-Path $SdkRoot 'emulator\emulator.exe'
Write-Host ''
Write-Host 'Hardware acceleration check:' -ForegroundColor Cyan
Invoke-Native { & $emulator -accel-check 2>&1 | ForEach-Object { "$_" } | Out-Host }
Write-Host 'If WHPX is reported as not installed: enable "Windows Hypervisor Platform" in' -ForegroundColor Yellow
Write-Host 'Windows Features (needs admin, then reboot) and enable virtualization in BIOS.' -ForegroundColor Yellow

Write-Step 'Optional: desktop shortcut with launcher window'
New-EmulatorShortcut -SdkRoot $SdkRoot -AvdName $AvdName

Write-Host ''
Write-Host "Done. AVD '$AvdName' created." -ForegroundColor Green
Write-Host 'Start it with the desktop shortcut, or from a NEW terminal:'
Write-Host "  emulator -avd $AvdName"
Write-Host '  add -no-window -no-audio for headless mode'
Write-Host 'For Expo: run "npx expo start" in your project and press "a".'
